# Generated by Django 6.0.1 on 2026-01-27 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(verbose_name='Relato do Cidadão')),
                ('tipo', models.CharField(choices=[('denuncia', 'Denúncia'), ('sugestao', 'Sugestão'), ('elogio', 'Elogio')], max_length=50)),
                ('anonimo', models.BooleanField(default=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
