# Generated by Django 6.0.1 on 2026-01-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacao',
            name='classificacao_ia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacao',
            name='tipo',
            field=models.CharField(choices=[('denuncia', 'Denúncia'), ('sugestao', 'Sugestão'), ('elogio', 'Elogio'), ('reclamacao', 'Reclamação')], max_length=50),
        ),
    ]
