# Generated by Django 6.0.1 on 2026-01-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0002_manifestacao_classificacao_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
